# Inventaire Kubernetes - Sample
# Copier vers production/ et adapter les IPs

all:
  hosts:
    # Control plane (master)
    master1:
      ansible_host: 10.0.0.10
      ip: 10.0.0.10
      access_ip: 10.0.0.10

    # Workers
    worker1:
      ansible_host: 10.0.0.11
      ip: 10.0.0.11
      access_ip: 10.0.0.11

    worker2:
      ansible_host: 10.0.0.12
      ip: 10.0.0.12
      access_ip: 10.0.0.12

  children:
    kube_control_plane:
      hosts:
        master1:

    kube_node:
      hosts:
        master1:
        worker1:
        worker2:

    etcd:
      hosts:
        master1:

    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:

    calico_rr:
      hosts: {}

  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
