apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gophish

resources:
  - ../../base
  - ingress.yml

patches:
  - path: secrets-patch.yml

commonLabels:
  environment: production
