# Configuration cluster Kubernetes

# Version
kube_version: v1.29.0

# Nom du cluster
cluster_name: cluster.local

# Container runtime
container_manager: containerd

# Reseau
kube_network_plugin: calico
kube_pods_subnet: 10.233.64.0/18
kube_service_addresses: 10.233.0.0/18

# DNS
dns_mode: coredns
enable_nodelocaldns: true

# API Server
kube_apiserver_port: 6443

# Addons
metrics_server_enabled: true
ingress_nginx_enabled: true
cert_manager_enabled: true

# MetalLB (LoadBalancer bare-metal)
metallb_enabled: true
metallb_speaker_enabled: true
metallb_protocol: layer2
metallb_ip_range:
  - "10.0.0.200-10.0.0.250"

# Stockage local
local_path_provisioner_enabled: true
