apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: APP_NAME

resources:
  - namespace.yml
  - deployment.yml
  - service.yml

commonLabels:
  app.kubernetes.io/name: APP_NAME
  app.kubernetes.io/managed-by: kustomize
