apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gophish

resources:
  - namespace.yml
  - secret.yml
  - mysql.yml
  - gophish.yml

commonLabels:
  app.kubernetes.io/name: gophish
  app.kubernetes.io/managed-by: kustomize
